POINTCLOUD_MINZOOM		= 0.5
POINTCLOUD_MAXZOOM		= 5

POINTCLOUD_MODE_CUBE		= 1
POINTCLOUD_MODE_POINTS		= 2
POINTCLOUD_MODE_HOLOGRAM	= 3

POINTCLOUD_SAMPLE_NONE 			= 0
POINTCLOUD_SAMPLE_NOISE 		= 1
POINTCLOUD_SAMPLE_FRONTFACING 	= 2
POINTCLOUD_SAMPLE_AUTOMAP 		= 3
POINTCLOUD_SAMPLE_SWEEPING 		= 4
POINTCLOUD_SAMPLE_SATMAP 		= 5